# justfile for building main.tex

default := "build"

build:
	xelatex -interaction=nonstopmode -halt-on-error -file-line-error -jobname=ShawalMbalireCV -output-directory=. main.tex
	xelatex -interaction=nonstopmode -halt-on-error -file-line-error -jobname=ShawalMbalireCV -output-directory=. main.tex

clean:
	rm -f *.aux *.log *.out *.toc *.pdf

view:
	if [ -f ShawalMbalireCV.pdf ]; then xdg-open ShawalMbalireCV.pdf; else echo "ShawalMbalireCV.pdf not found"; fi
