# justfile for building main.tex

default := "build"

build:
	xelatex -interaction=nonstopmode -halt-on-error -file-line-error -output-directory=. main.tex
	xelatex -interaction=nonstopmode -halt-on-error -file-line-error -output-directory=. main.tex

clean:
	rm -f *.aux *.log *.out *.toc *.pdf

view:
	if [ -f main.pdf ]; then xdg-open main.pdf; else echo "main.pdf not found"; fi
